---
abstract: 'Object oriented interface to Data::TreeDumper'
author:
  - 'Nadim Khemir <nadim.khemir@gmail.com>'
build_requires:
  Test: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.016, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Data-TreeDumper-OO
requires:
  Carp: '0'
  Data::TreeDumper: '0.24'
  Exporter: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/neilbowers/Data-TreeDumper-OO
  repository: https://github.com/neilbowers/Data-TreeDumper-OO.git
version: '0.08'
